# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src

resources:
- repo: self

variables:
  tag: '$(Build.BuildNumber)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build and push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker hub mrtncls'
        repository: 'mrtncls/solar2influxdb'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/src/Dockerfile'
        tags: |
          $(tag)
          latest
