# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src

resources:
- repo: self

variables:
  tag: '$(Build.BuildNumber)'

stages:
- stage: TestAndBuild
  displayName: Run tests & Build image
  jobs:
  - job: TestAndBuild
    displayName: Run tests & Build image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*.Tests.csproj'
        testRunTitle: 'Unittests'
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker hub mrtncls'
        repository: 'mrtncls/solar2influxdb'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/src/Dockerfile'
        tags: |
          $(tag)
          latest
